/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-27 08:54:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"x-admin-sm\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>欢迎页面-X-admin2.2</title>\r\n");
      out.write("        <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./css/font.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./css/xadmin.css\">\r\n");
      out.write("        <script src=\"./lib/layui/layui.js\" charset=\"utf-8\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"./js/xadmin.js\"></script>\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"https://cdn.staticfile.org/html5shiv/r29/html5.min.js\"></script>\r\n");
      out.write("          <script src=\"https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"x-nav\">\r\n");
      out.write("          <span class=\"layui-breadcrumb\">\r\n");
      out.write("            <a href=\"\">首页</a>\r\n");
      out.write("            <a href=\"\">演示</a>\r\n");
      out.write("            <a>\r\n");
      out.write("              <cite>导航元素</cite></a>\r\n");
      out.write("          </span>\r\n");
      out.write("          <a class=\"layui-btn layui-btn-small\" style=\"line-height:1.6em;margin-top:3px;float:right\" onclick=\"location.reload()\" title=\"刷新\">\r\n");
      out.write("            <i class=\"layui-icon layui-icon-refresh\" style=\"line-height:30px\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"layui-fluid\">\r\n");
      out.write("            <div class=\"layui-row layui-col-space15\">\r\n");
      out.write("                <div class=\"layui-col-md12\">\r\n");
      out.write("                    <div class=\"layui-card\">\r\n");
      out.write("                        <div class=\"layui-card-body \">\r\n");
      out.write("                            <form class=\"layui-form layui-col-space5\">\r\n");
      out.write("                                <div class=\"layui-inline layui-show-xs-block\">\r\n");
      out.write("                                    <input class=\"layui-input\"  autocomplete=\"off\" placeholder=\"开始日\" name=\"start\" id=\"start\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"layui-inline layui-show-xs-block\">\r\n");
      out.write("                                    <input class=\"layui-input\"  autocomplete=\"off\" placeholder=\"截止日\" name=\"end\" id=\"end\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"layui-inline layui-show-xs-block\">\r\n");
      out.write("                                    <input type=\"text\" name=\"username\"  placeholder=\"请输入用户名\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"layui-inline layui-show-xs-block\">\r\n");
      out.write("                                    <button class=\"layui-btn\"  lay-submit=\"\" lay-filter=\"sreach\"><i class=\"layui-icon\">&#xe615;</i></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"layui-card-header\">\r\n");
      out.write("                            <button class=\"layui-btn layui-btn-danger\" onclick=\"delAll()\"><i class=\"layui-icon\"></i>批量删除</button>\r\n");
      out.write("                            <button class=\"layui-btn\" onclick=\"xadmin.open('添加用户','./admin-add.html',600,400)\"><i class=\"layui-icon\"></i>添加</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"layui-card-body \">\r\n");
      out.write("                            <table class=\"layui-table layui-form\">\r\n");
      out.write("                              <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                  <th>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"\"  lay-skin=\"primary\">\r\n");
      out.write("                                  </th>\r\n");
      out.write("                                  <th>ID</th>\r\n");
      out.write("                                  <th>登录名</th>\r\n");
      out.write("                                  <th>手机</th>\r\n");
      out.write("                                  <th>邮箱</th>\r\n");
      out.write("                                  <th>角色</th>\r\n");
      out.write("                                  <th>加入时间</th>\r\n");
      out.write("                                  <th>状态</th>\r\n");
      out.write("                                  <th>操作</th>\r\n");
      out.write("                              </thead>\r\n");
      out.write("                              <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                  <td>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"\"  lay-skin=\"primary\">\r\n");
      out.write("                                  </td>\r\n");
      out.write("                                  <td>1</td>\r\n");
      out.write("                                  <td>admin</td>\r\n");
      out.write("                                  <td>18925139194</td>\r\n");
      out.write("                                  <td>113664000@qq.com</td>\r\n");
      out.write("                                  <td>超级管理员</td>\r\n");
      out.write("                                  <td>2017-01-01 11:11:42</td>\r\n");
      out.write("                                  <td class=\"td-status\">\r\n");
      out.write("                                    <span class=\"layui-btn layui-btn-normal layui-btn-mini\">已启用</span></td>\r\n");
      out.write("                                  <td class=\"td-manage\">\r\n");
      out.write("                                    <a onclick=\"member_stop(this,'10001')\" href=\"javascript:;\"  title=\"启用\">\r\n");
      out.write("                                      <i class=\"layui-icon\">&#xe601;</i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a title=\"编辑\"  onclick=\"xadmin.open('编辑','admin-edit.html')\" href=\"javascript:;\">\r\n");
      out.write("                                      <i class=\"layui-icon\">&#xe642;</i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a title=\"删除\" onclick=\"member_del(this,'要删除的id')\" href=\"javascript:;\">\r\n");
      out.write("                                      <i class=\"layui-icon\">&#xe640;</i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                  </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                              </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"layui-card-body \">\r\n");
      out.write("                            <div class=\"page\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                  <a class=\"prev\" href=\"\">&lt;&lt;</a>\r\n");
      out.write("                                  <a class=\"num\" href=\"\">1</a>\r\n");
      out.write("                                  <span class=\"current\">2</span>\r\n");
      out.write("                                  <a class=\"num\" href=\"\">3</a>\r\n");
      out.write("                                  <a class=\"num\" href=\"\">489</a>\r\n");
      out.write("                                  <a class=\"next\" href=\"\">&gt;&gt;</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("    </body>\r\n");
      out.write("    <script>\r\n");
      out.write("      layui.use(['laydate','form'], function(){\r\n");
      out.write("        var laydate = layui.laydate;\r\n");
      out.write("        var form = layui.form;\r\n");
      out.write("        \r\n");
      out.write("        //执行一个laydate实例\r\n");
      out.write("        laydate.render({\r\n");
      out.write("          elem: '#start' //指定元素\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //执行一个laydate实例\r\n");
      out.write("        laydate.render({\r\n");
      out.write("          elem: '#end' //指定元素\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("       /*用户-停用*/\r\n");
      out.write("      function member_stop(obj,id){\r\n");
      out.write("          layer.confirm('确认要停用吗？',function(index){\r\n");
      out.write("\r\n");
      out.write("              if($(obj).attr('title')=='启用'){\r\n");
      out.write("\r\n");
      out.write("                //发异步把用户状态进行更改\r\n");
      out.write("                $(obj).attr('title','停用')\r\n");
      out.write("                $(obj).find('i').html('&#xe62f;');\r\n");
      out.write("\r\n");
      out.write("                $(obj).parents(\"tr\").find(\".td-status\").find('span').addClass('layui-btn-disabled').html('已停用');\r\n");
      out.write("                layer.msg('已停用!',{icon: 5,time:1000});\r\n");
      out.write("\r\n");
      out.write("              }else{\r\n");
      out.write("                $(obj).attr('title','启用')\r\n");
      out.write("                $(obj).find('i').html('&#xe601;');\r\n");
      out.write("\r\n");
      out.write("                $(obj).parents(\"tr\").find(\".td-status\").find('span').removeClass('layui-btn-disabled').html('已启用');\r\n");
      out.write("                layer.msg('已启用!',{icon: 5,time:1000});\r\n");
      out.write("              }\r\n");
      out.write("              \r\n");
      out.write("          });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /*用户-删除*/\r\n");
      out.write("      function member_del(obj,id){\r\n");
      out.write("          layer.confirm('确认要删除吗？',function(index){\r\n");
      out.write("              //发异步删除数据\r\n");
      out.write("              $(obj).parents(\"tr\").remove();\r\n");
      out.write("              layer.msg('已删除!',{icon:1,time:1000});\r\n");
      out.write("          });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      function delAll (argument) {\r\n");
      out.write("\r\n");
      out.write("        var data = tableCheck.getData();\r\n");
      out.write("  \r\n");
      out.write("        layer.confirm('确认要删除吗？'+data,function(index){\r\n");
      out.write("            //捉到所有被选中的，发异步进行删除\r\n");
      out.write("            layer.msg('删除成功', {icon: 1});\r\n");
      out.write("            $(\".layui-form-checked\").not('.header').parents('tr').remove();\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>var _hmt = _hmt || []; (function() {\r\n");
      out.write("        var hm = document.createElement(\"script\");\r\n");
      out.write("        hm.src = \"https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190\";\r\n");
      out.write("        var s = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("        s.parentNode.insertBefore(hm, s);\r\n");
      out.write("      })();</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
