/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-25 10:12:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"x-admin-sm\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>后台登录-X-admin2.2</title>\r\n");
      out.write("        <meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi\" />\r\n");
      out.write("        <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./css/font.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./css/xadmin.css\">\r\n");
      out.write("        <!-- <link rel=\"stylesheet\" href=\"./css/theme5.css\"> -->\r\n");
      out.write("        <script src=\"./lib/layui/layui.js\" charset=\"utf-8\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"./js/xadmin.js\"></script>\r\n");
      out.write("        <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"https://cdn.staticfile.org/html5shiv/r29/html5.min.js\"></script>\r\n");
      out.write("          <script src=\"https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("        <script>\r\n");
      out.write("            // 是否开启刷新记忆tab功能\r\n");
      out.write("            // var is_remember = false;\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"index\">\r\n");
      out.write("        <!-- 顶部开始 -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"./index.html\">X-admin v2.2</a></div>\r\n");
      out.write("            <div class=\"left_open\">\r\n");
      out.write("                <a><i title=\"展开左侧栏\" class=\"iconfont\">&#xe699;</i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"layui-nav left fast-add\" lay-filter=\"\">\r\n");
      out.write("                <li class=\"layui-nav-item\">\r\n");
      out.write("                    <a href=\"javascript:;\">+新增</a>\r\n");
      out.write("                    <dl class=\"layui-nav-child\">\r\n");
      out.write("                        <!-- 二级菜单 -->\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.open('最大化','http://www.baidu.com','','',true)\">\r\n");
      out.write("                                <i class=\"iconfont\">&#xe6a2;</i>弹出最大化</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.open('弹出自动宽高','http://www.baidu.com')\">\r\n");
      out.write("                                <i class=\"iconfont\">&#xe6a8;</i>弹出自动宽高</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.open('弹出指定宽高','http://www.baidu.com',500,300)\">\r\n");
      out.write("                                <i class=\"iconfont\">&#xe6a8;</i>弹出指定宽高</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.add_tab('在tab打开','member-list.html')\">\r\n");
      out.write("                                <i class=\"iconfont\">&#xe6b8;</i>在tab打开</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.add_tab('在tab打开刷新','member-del.html',true)\">\r\n");
      out.write("                                <i class=\"iconfont\">&#xe6b8;</i>在tab打开刷新</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"layui-nav right\" lay-filter=\"\">\r\n");
      out.write("                <li class=\"layui-nav-item\">\r\n");
      out.write("                    <a href=\"javascript:;\">admin</a>\r\n");
      out.write("                    <dl class=\"layui-nav-child\">\r\n");
      out.write("                        <!-- 二级菜单 -->\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.open('个人信息','http://www.baidu.com')\">个人信息</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a onclick=\"xadmin.open('切换帐号','http://www.baidu.com')\">切换帐号</a></dd>\r\n");
      out.write("                        <dd>\r\n");
      out.write("                            <a href=\"./login.html\">退出</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"layui-nav-item to-index\">\r\n");
      out.write("                    <a href=\"/\">前台首页</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 顶部结束 -->\r\n");
      out.write("        <!-- 中部开始 -->\r\n");
      out.write("        <!-- 左侧菜单开始 -->\r\n");
      out.write("        <div class=\"left-nav\">\r\n");
      out.write("            <div id=\"side-nav\">\r\n");
      out.write("                <ul id=\"nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"会员管理\">&#xe6b8;</i>\r\n");
      out.write("                            <cite>书籍管理</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('统计页面','welcome1.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>统计页面</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('会员列表(静态表格)','member-list.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>会员列表(静态表格)</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('会员列表(动态表格)','member-list1.html',true)\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>会员列表(动态表格)</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('会员删除','member-del.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>会员删除</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:;\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe70b;</i>\r\n");
      out.write("                                    <cite>会员管理</cite>\r\n");
      out.write("                                    <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                                <ul class=\"sub-menu\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a onclick=\"xadmin.add_tab('会员删除','member-del.html')\">\r\n");
      out.write("                                            <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                            <cite>会员删除</cite></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a onclick=\"xadmin.add_tab('等级管理','member-list1.html')\">\r\n");
      out.write("                                            <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                            <cite>等级管理</cite></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"订单管理\">&#xe723;</i>\r\n");
      out.write("                            <cite>用户管理</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('订单列表','order-list.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>订单列表</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('订单列表1','order-list1.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>订单列表1</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"分类管理\">&#xe723;</i>\r\n");
      out.write("                            <cite>分类管理</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('多级分类','cate.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>多级分类</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"城市联动\">&#xe723;</i>\r\n");
      out.write("                            <cite>城市联动</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('三级地区联动','city.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>三级地区联动</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"管理员管理\">&#xe726;</i>\r\n");
      out.write("                            <cite>管理员管理</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('管理员列表','admin-list.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>管理员列表</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('角色管理','admin-role.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>角色管理</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('权限分类','admin-cate.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>权限分类</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('权限管理','admin-rule.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>权限管理</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"系统统计\">&#xe6ce;</i>\r\n");
      out.write("                            <cite>系统统计</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('拆线图','echarts1.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>拆线图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('拆线图','echarts2.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>拆线图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('地图','echarts3.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>地图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('饼图','echarts4.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>饼图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('雷达图','echarts5.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>雷达图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('k线图','echarts6.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>k线图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('热力图','echarts7.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>热力图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('仪表图','echarts8.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>仪表图</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"图标字体\">&#xe6b4;</i>\r\n");
      out.write("                            <cite>图标字体</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('图标对应字体','unicode.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>图标对应字体</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"其它页面\">&#xe6b4;</i>\r\n");
      out.write("                            <cite>其它页面</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"login.html\" target=\"_blank\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>登录页面</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('错误页面','error.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>错误页面</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('示例页面','demo.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>示例页面</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('更新日志','log.html')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>更新日志</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\">\r\n");
      out.write("                            <i class=\"iconfont left-nav-li\" lay-tips=\"第三方组件\">&#xe6b4;</i>\r\n");
      out.write("                            <cite>layui第三方组件</cite>\r\n");
      out.write("                            <i class=\"iconfont nav_right\">&#xe697;</i></a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('滑块验证','https://fly.layui.com/extend/sliderVerify/')\" target=\"\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>滑块验证</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('富文本编辑器','https://fly.layui.com/extend/layedit/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>富文本编辑器</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('eleTree 树组件','https://fly.layui.com/extend/eleTree/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>eleTree 树组件</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('图片截取','https://fly.layui.com/extend/croppers/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>图片截取</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('formSelects 4.x 多选框','https://fly.layui.com/extend/formSelects/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>formSelects 4.x 多选框</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('Magnifier 放大镜','https://fly.layui.com/extend/Magnifier/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>Magnifier 放大镜</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a onclick=\"xadmin.add_tab('notice 通知控件','https://fly.layui.com/extend/notice/')\">\r\n");
      out.write("                                    <i class=\"iconfont\">&#xe6a7;</i>\r\n");
      out.write("                                    <cite>notice 通知控件</cite></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- <div class=\"x-slide_left\"></div> -->\r\n");
      out.write("        <!-- 左侧菜单结束 -->\r\n");
      out.write("        <!-- 右侧主体开始 -->\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div class=\"layui-tab tab\" lay-filter=\"xbs_tab\" lay-allowclose=\"false\">\r\n");
      out.write("                <ul class=\"layui-tab-title\">\r\n");
      out.write("                    <li class=\"home\">\r\n");
      out.write("                        <i class=\"layui-icon\">&#xe68e;</i>我的桌面</li></ul>\r\n");
      out.write("                <div class=\"layui-unselect layui-form-select layui-form-selected\" id=\"tab_right\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dd data-type=\"this\">关闭当前</dd>\r\n");
      out.write("                        <dd data-type=\"other\">关闭其它</dd>\r\n");
      out.write("                        <dd data-type=\"all\">关闭全部</dd></dl>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"layui-tab-content\">\r\n");
      out.write("                    <div class=\"layui-tab-item layui-show\">\r\n");
      out.write("                        <iframe src='./welcome.html' frameborder=\"0\" scrolling=\"yes\" class=\"x-iframe\"></iframe>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"tab_show\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"page-content-bg\"></div>\r\n");
      out.write("        <style id=\"theme_style\"></style>\r\n");
      out.write("        <!-- 右侧主体结束 -->\r\n");
      out.write("        <!-- 中部结束 -->\r\n");
      out.write("        <script>//百度统计可去掉\r\n");
      out.write("            var _hmt = _hmt || []; (function() {\r\n");
      out.write("                var hm = document.createElement(\"script\");\r\n");
      out.write("                hm.src = \"https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190\";\r\n");
      out.write("                var s = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("                s.parentNode.insertBefore(hm, s);\r\n");
      out.write("            })();</script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
